### PR TITLE
exoscale: egoscale v0.12.2

### PR DESCRIPTION
**Pull request by greut**
## Description

Bump egoscale library for the Exoscale driver to v0.12 (previously #6)

We will be working to have our integration tests running on Travis so they are publicly available.

Best!

## Related issue(s)

It would be nice to update dep to 0.5 as the format changed.

### CODE REVIEW

**Comment by afbjorklund** [comment]
Would it make sense to move this driver to an external repository instead ?

**Comment by greut** [comment]
@afbjorklund it would probably make sense that any drivers are made external considering Docker Inc actual position.

**Comment by afbjorklund** [comment]
It would also make it easier, to only host drivers here and not change the "API" (i.e. libmachine) ?
Even if updating the bundled drivers doesn't _actually_ change libmachine, currently they are combined...

Anyway, adding some `make` scaffolding and creating "machine-drivers/docker-machine-driver-exoscale" could be an easier way to implement this, than to add a massive (in lines of code) merge to "machine".

**Comment by greut** [comment]
@afbjorklund what about? https://github.com/exoscale/docker-machine-driver-exo

**Comment by afbjorklund** [comment]
@greut : added https://github.com/machine-drivers/docker-machine-driver-exo for this

**Pull request closed without merging**
