### PR TITLE
add 127.0.0.1 to the certs

### PR DESCRIPTION
**Pull request by medyagh**
because of this https://github.com/kubernetes/minikube/pull/7021

### CODE REVIEW

**Comment by afbjorklund** [comment]
@medyagh : it's not clear why it is not enough to have "localhost" (as per 1df80ba111f0234686a1a35e2544ab7154ef3870) ?
It would resolve to either `127.0.0.1`(IPv4) or `[::1]` (IPv6), so it's really the same

The main difference with this driver is that it is **not** connecting "from the machine itself"
Rather it is connecting through a tunnel, but it could still use "localhost" for the hostname

**Comment by medyagh** [comment]
This change fixes the minikube issue for docker driver please see the pr description for exact error

**Comment by medyagh** [comment]
Without this pr I get this error for connecting to docker daemon using docker driver

Error during connect: Get https://127.0.0.1:32799

**Comment by afbjorklund** [comment]
I suppose there is no harm in adding another default cert for localhost/127.0.0.1.
Normally it will use the IP anyway, and these two other ones are for "special cases"

Can you rebase/cherry-pick ? Seems like 2 commits can be dropped, leave e8ba17976bbe003f0e8f15f02fc8fd805b22f0b6
There is no new tagging done on the master branch, so that is why it looks a bit weird.

i.e. [v0.16.2](https://github.com/docker/machine/releases/tag/v0.16.2) is the _same_ as https://github.com/docker/machine/commit/b170508bf44c3405e079e26d5fdffe35a64c6972 (v0.16.2^), but with a version stamp...

**Comment by afbjorklund** [comment]
@medyagh : any luck with this ? Also, it is confusing when you do your own (patched) releases...
It is _supposed_ to look weird in go modules, because go doesn't support git tagging on branches.

But having two _different_ machine `v0.16.2` isn't great either: https://github.com/machine-drivers/machine/compare/v0.16.2...medyagh:v0.16.2
Especially if there are no new binaries. https://github.com/docker/machine/releases/tag/v0.16.2

- docker-machine-Darwin-x86_64
- docker-machine-Linux-aarch64
- docker-machine-Linux-armhf
- docker-machine-Linux-x86_64
- docker-machine-Windows-i386.exe
- docker-machine-Windows-x86_64.exe

Would be great to get this confusion sorted before minikube 1.9.0 is released (now in beta).

```
	github.com/docker/machine => github.com/medyagh/machine v0.16.4
```

https://github.com/medyagh/machine/releases/tag/v0.16.4

**Pull request merged**
