### PR TITLE
Update from 0.16.0 to 0.16.1

### PR DESCRIPTION
**Pull request by afbjorklund**
Includes fix for #12 : 1dae68b7e1acc3e50a9710da9176628948dbaf11 --> https://github.com/docker/machine/commit/55bfb59b67e7db9c058d6a973a46c7a2d32f0d17
But not (yet...) #10 : 6f34be407f21920decfd3c031f64e500e66979da --> https://github.com/docker/machine/commit/10d5119334dc866702c2b71458fc061f4a7d778d

### CODE REVIEW

**Comment by tstromberg** [comment]
Thanks for doing this! 'm really eager about getting this merged so that ssh exit codes work properly in minikube.

**Comment by praveenkumar** [comment]
Thanks for rebase. Merging it now. @tstromberg let me know if you don't have admin access for this repo to merge the PR ( you should have it).

**Comment by afbjorklund** [comment]
@praveenkumar : Thanks!

Do you think we should keep using the machine-drivers/machine source, or go back to docker/machine ?

Once `v0.17.0` is out there will be no differences left at all, and even now it is only the hyper-v l10n issue:

https://github.com/docker/machine/compare/v0.16.1...machine-drivers:master

For minishift is already using the rebased revision, but for minikube it is exactly the same revision.

Just that it doesn't seem to be any reason left, to keep this repository different from the upstream...

**Pull request merged**
